// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static void appendAtTheEndBuildString(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.AppendAtTheEndBuildString").withParams(params).execute(context);
	}
	public static void fileBufferBuildString(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.FileBufferBuildString").withParams(params).execute(context);
	}
	public static java.lang.String getEntityToString(IContext context, myfirstmodule.proxies.BusinessEntity _entity)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Entity", _entity == null ? null : _entity.getMendixObject());
		return (java.lang.String) Core.microflowCall("MyFirstModule.GetEntityToString").withParams(params).execute(context);
	}
	public static void justRead(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.JustRead").withParams(params).execute(context);
	}
	public static void memoryBufferBuildString(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.MemoryBufferBuildString").withParams(params).execute(context);
	}
	public static void sUB_CreateData(IContext context, myfirstmodule.proxies.NumberOfRecords _numberOfRecords)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("NumberOfRecords", _numberOfRecords == null ? null : _numberOfRecords.getMendixObject());
		Core.microflowCall("MyFirstModule.SUB_CreateData").withParams(params).execute(context);
	}
	public static java.lang.Long sUB_FileBufferBuildString(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		return (java.lang.Long) Core.microflowCall("MyFirstModule.SUB_FileBufferBuildString").withParams(params).execute(context);
	}
	public static java.lang.Long sUB_TempStorageBuildString(IContext context, myfirstmodule.proxies.OutputDocument _outputDocument)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("OutputDocument", _outputDocument == null ? null : _outputDocument.getMendixObject());
		return (java.lang.Long) Core.microflowCall("MyFirstModule.SUB_TempStorageBuildString").withParams(params).execute(context);
	}
	public static void tempStorageBuildString(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.TempStorageBuildString").withParams(params).execute(context);
	}
	public static void theStartingPointBuildString(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.TheStartingPointBuildString").withParams(params).execute(context);
	}
}
