// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.nio.charset.Charset;
import java.nio.file.Files;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class AppendStringToDocument2 extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __Document;
	private system.proxies.FileDocument Document;
	private myfirstmodule.proxies.ENUM_AppendStringAction Action;
	private java.lang.String StringToAppend;

	public AppendStringToDocument2(IContext context, IMendixObject Document, java.lang.String Action, java.lang.String StringToAppend)
	{
		super(context);
		this.__Document = Document;
		this.Action = Action == null ? null : myfirstmodule.proxies.ENUM_AppendStringAction.valueOf(Action);
		this.StringToAppend = StringToAppend;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.Document = this.__Document == null ? null : system.proxies.FileDocument.initialize(getContext(), __Document);

		// BEGIN USER CODE
		return appendStringToDocument();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AppendStringToDocument2";
	}

	// BEGIN EXTRA CODE
	
	private Void appendStringToDocument() throws Exception
	{
		String tempPath = System.getProperty("java.io.tmpdir");
		String filePath = tempPath + "/Doc-" + Document.getFileID() + ".tmp";

		File file = new File(filePath);

		try
		{
			switch (Action)
			{
				case Initialise:
					if (file.exists())
						file.delete();
					if (file.createNewFile() == false)
						throw new Exception("Failed to create temp file: filePath");
					break;
					
				case AppendString:
					FileOutputStream out = new FileOutputStream(file, true);
					out.write(StringToAppend.getBytes(Charset.forName("UTF-8")));
					out.close();
					break;
					
				case Finish:
					FileInputStream in = new FileInputStream(file);
					Core.storeFileDocumentContent(getContext(), __Document, in);
					in.close();
					file.delete();
					break;
			}
		}
		catch (Exception e)
		{
			if (file.exists())
				file.delete();
		}
		
		return null;
	}
	// END EXTRA CODE
}
