// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import java.io.ByteArrayInputStream;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import myfirstmodule.proxies.StringValue;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ListToString extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __Document;
	private system.proxies.FileDocument Document;
	private java.util.List<IMendixObject> __Strings;
	private java.util.List<myfirstmodule.proxies.StringValue> Strings;

	public ListToString(IContext context, IMendixObject Document, java.util.List<IMendixObject> Strings)
	{
		super(context);
		this.__Document = Document;
		this.__Strings = Strings;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.Document = this.__Document == null ? null : system.proxies.FileDocument.initialize(getContext(), __Document);

		this.Strings = java.util.Optional.ofNullable(this.__Strings)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(__StringsElement -> myfirstmodule.proxies.StringValue.initialize(getContext(), __StringsElement))
			.collect(java.util.stream.Collectors.toList());

		// BEGIN USER CODE
		StringBuffer buffer = new StringBuffer();
		for (StringValue stringValue: Strings)
		{
			buffer.append(stringValue.getValue());
		}
		
		ByteArrayInputStream stream = new ByteArrayInputStream(buffer.toString().getBytes("UTF-8"));
		
		Core.storeFileDocumentContent(getContext(), __Document, stream);
		
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ListToString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
